spring:
   datasource:
     url: jdbc:mysql://192.168.0.150:3306/theflash?useSSL=false
     username: dbadmin
     password: 2017admin*QMX
     driver-class-name: com.mysql.jdbc.Driver
server:
  context-path: /stumanage
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml



