spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stumanage?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
    timeout: 0


server:
  context-path: /stumanage
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml



