spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: /static
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stumanage?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080


