spring:
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/stumanage?useUnicode=true&characterEncoding=UTF-8useUnicode=true&characterEncoding=UTF-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
server:
  context-path: /stumanage
  port: 8080
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations:
      classpath*:mapper/**/*Mapper.xml






